delete compiles/d
EcoJulia/BiobakeryUtils.jl pull request #105
Opened 2022-07-01 22:03 UTC by anikaluo

closes #103

2022-07-02 00:58 UTC, kescobo requested changes

2022-07-02 00:58 UTC, kescobo commented on src/metaphlan.jl
> +Combines a MetaPhlAn file into a CommunityProfile.
```suggestion
Creates a CommunityProfile from a MetaPhlAn output file.
```

2022-07-02 00:58 UTC, kescobo commented on src/metaphlan.jl
> +Can select data according to taxonomic rank. If rank not given, all data is combined.
```suggestion
Can select data according to taxonomic rank. If rank not given, all data is used.
```

2022-07-02 00:58 UTC, kescobo commented on src/metaphlan.jl
> +Combines MetaPhlAn profiles from a merged table into a CommunityProfile.
```suggestion
Reads in MetaPhlAn profiles from a merged table into a CommunityProfile.
```

2022-07-02 00:58 UTC, kescobo commented on src/metaphlan.jl
> +Can select data according to taxonomic rank. If rank not given, all data is combined.
```suggestion
Can select data according to taxonomic rank. If rank not given, all data is used.
```

2022-07-02 12:20 UTC, anikaluo commented
Yeah, those sentences make much more sense now.

2022-07-03 19:31 UTC, kescobo approved these changes

2022-07-03 19:32 UTC, merged